Repository easysql/easy_sql, pull requests merged in 2022-08, with the labels that each got.

#33 ci: support auto release and publish package
  .github/mergify.yml
  .github/release-drafter.yml
  .github/workflows/draft-release.yaml
  .github/workflows/release.yaml
  pyproject.old.toml
  pyproject.toml
Labels: pr-build

#34 ci: fix ci cache miss
  .github/workflows/build.yaml
  .github/workflows/release.yaml
  README.md
  pyproject.toml
  setup.cfg
Labels: pr-build, pr-feature

#36 fix: recover bigquery-related codes lost in previous merge.
  easy_sql/sql_processor/backend/sql_dialect/bigquery.py
Labels: pr-bugfix

#37 fix: use psycopg2 instead binary as the dependency of postgresql backend
  poetry.lock
  pyproject.toml
Labels: pr-bugfix

#38 fix: fix get excel formula value
  easy_sql/sql_tester.py
Labels: pr-bugfix
